NumPy is a linear algebra library. It is powerful and extremely fast and integrates with C/C++.

In [2]:
import numpy as np
np.__version__

'1.23.5'

**1) NumPy Arrays

NumPy Arrays can be used to form vectors and matrices

In [3]:
my_list = [-1, 0, 1]
my_list, type(my_list)

([-1, 0, 1], list)

In [4]:
my_array = np.array(my_list)
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [5]:
# lets create a 2d array
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my_2d_array, type(my_2d_array)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

In [6]:
# lets create a matrix from the 2d array
my_matrix = np.array(my_2d_array)
my_matrix, type(my_matrix)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

**1.2) NumPy Arrays from Tuples

In [9]:
my_list = np.array((1, 2, 3))
my_list

array([1, 2, 3])

**1.3) NumPy Array built-in methods**
Its common to create NumPy arrays using its own built-in methods.
They are much simpler and faster

**1.3.1) arange()**
arange is similar to range().
- used to generate evenly-spaced values in an interval
- syntax: arange([start ,] stop[, step,] dtype=None)

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.arange(0, 10, 2, float)

array([0., 2., 4., 6., 8.])

**1.3.2) linspace()**
similar to arange(), but the third argument for linspace is the number of points we want (instead of the step size)

In [16]:
np.linspace(1, 15, 4)

array([ 1.        ,  5.66666667, 10.33333333, 15.        ])

In [21]:
# a 4th optional argument returns the calculated step size alongside the array
my_linspace = np.linspace(1, 15, 3, retstep=True)
print('array is {arr}'.format(arr=my_linspace[0]))
print('step size is {step}'.format(step=my_linspace[1]))

array is [ 1.  8. 15.]
step size is 7.0


**1.3.3) zeros()**
Used to create an array or matrix with all zeroes

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((2, 3)) # row x col is passed in a tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

**1.3.4) ones()**
Used to create an array or matrix of ones (similar to zeros)

In [25]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.ones((2, 3)) # row x col is passed in a tuple

array([[1., 1., 1.],
       [1., 1., 1.]])

**1.3.5) eye()**
Identity matrix, only one param is needed because its always a square matrix

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**1.3.6) rand()**
Create an array of a given shape and pick values over a uniform distribution

In [28]:
np.random.rand(3)

array([0.58023145, 0.97584486, 0.44892061])

In [29]:
np.random.rand(2, 3) # row x col, no tuple this time

array([[0.02507535, 0.57262793, 0.43538384],
       [0.9526066 , 0.93865468, 0.41688845]])

**1.3.7) randn()**
Create an array of a given shape and pick values over a normal/Gaussian distribution

In [30]:
np.random.randn(3)

array([-1.68798546,  0.1475801 ,  0.92383748])

In [31]:
np.random.randn(2, 3)

array([[ 1.03714604,  1.43054483,  1.09180385],
       [ 0.03612585, -1.1193925 , -1.58284574]])

**1.3.8) randint()**
Create an array of random ints from low (inclusive) to high (exclusive)

In [34]:
np.random.randint(1, 100)

78

In [35]:
# a third optional argument generates an array of random ints if provided
np.random.randint(1, 100, 10)

array([97, 39, 20, 36, 86,  9, 31, 34, 12, 25])