1) What is the major difference between "Vector" and "Matrix"?

A vector is 1-D array of numbers
A matrix is 2-D array of numbers

2) How to import NumPy library?

In [3]:
import numpy as np
np.__version__

'1.23.5'

3) Convert the given Python list into NumPy array and check is data type.

In [13]:
list_1 = [1, 2, 3, 4, 5]
list_1, type(list_1)

([1, 2, 3, 4, 5], list)

In [16]:
list_2 = np.array(list_1)
np.array(list_2), type(np.array(list_2))

(array([1, 2, 3, 4, 5]), numpy.ndarray)

4) Generate array [0,1,2,3,4,5] using arange()

In [17]:
np.arange(0, 6)

array([0, 1, 2, 3, 4, 5])

5) Generate an array of 5 zeros

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
6) Generate a 4x4 matrix of zeros

In [20]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

7) Generate [1., 1., 1., 1., 1.]

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

8) Generate an array of "5" tens

In [26]:
np.ones(5) + 9

array([10., 10., 10., 10., 10.])

9) Use arange() to generate an array of even numbers between (50, 100)

In [29]:
np.arange(52, 100, 2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

10) Generate an array of 10 linearly spaced points between 0 and 1. Output the step size as well

In [30]:
arr = np.linspace(0, 1, 10, retstep=True)
arr

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

11) Perform the following tasks:
- Generate a vector array of 25 numbers using arange()
- Convert the vector array into 2D matrix using reshape
- Can we use shape instead of reshape as well?

In [37]:
vector = np.arange(25)
vector
#vector.reshape(5, 5) # works
vector.shape = (5, 5) # works
vector

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

12) Generate a 5x5 matrix containing numbers from 0.1 to 2.5

In [40]:
matrix = np.linspace(0.1, 2.5, 25).reshape(5, 5)
matrix

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

13) Generate a 5x5 matrix container numbers from 0 to 24. Print the step size

In [50]:
arr = np.linspace(0, 24, 25, retstep=True)
print(arr[0].reshape(5, 5))
print('Step size is ', arr[1])

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
Step size is  1.0


14) What is the main difference between linspace() and arange()?
- arange takes third argument as step size
- linspace takes third arguments as number of points we want

15) How to generate a single random number using NumPy built in function()

In [53]:
np.random.rand(1)

array([0.90430072])

16) Generate a 7x5 matrix of 35 random numbers

In [57]:
np.random.rand(7, 5)

array([[0.60459132, 0.49631172, 0.63658508, 0.53493018, 0.37346977],
       [0.65923259, 0.8887218 , 0.21851662, 0.95782234, 0.93488718],
       [0.5447538 , 0.10437195, 0.65062038, 0.97977896, 0.68558444],
       [0.95642025, 0.28886883, 0.77865217, 0.91755889, 0.40334901],
       [0.69080035, 0.40508768, 0.46158221, 0.18091505, 0.39338416],
       [0.44253653, 0.67554998, 0.93970704, 0.4039177 , 0.03230396],
       [0.28429157, 0.9350722 , 0.62210499, 0.37262486, 0.22336125]])

17) Generate the identity matrix and times it by 5

In [61]:
np.eye(5) * 5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

18) Generate a 6x5 matrix containing numbers from 0 to 29

In [63]:
arr = np.arange(0, 30).reshape(6, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [66]:
# slice a 3x3 matrix from bottom right
arr[3:,2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [67]:
# get number 29
arr[3:,2:][2, 2]

29

In [72]:
# get a 3x1 vector from container 1, 6, 11
arr[0:3, 1].reshape(3, 1)

array([[ 1],
       [ 6],
       [11]])

In [73]:
# get the third row
arr[2]

array([10, 11, 12, 13, 14])

In [74]:
# get the third and fourth rows
arr[[2, 3]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

19) Can u calculate the sum of all the numbers in the above array?

In [101]:
total = 0
shape = arr.shape
for i in range(shape[0]):
    for j in range(shape[1]):
        total += arr[i][j]
print(total)
print(arr.sum())

435
435


20) Calculate the sum of all the rows and columns in above array

In [98]:
print('Row sum: ', arr.sum(axis=1))
print('Col sum: ', arr.sum(axis=0))

Row sum:  [ 10  35  60  85 110 135]
Col sum:  [75 81 87 93 99]


21) Calculate the standard deviation of the values in above array

In [100]:
arr.std()

8.65544144839919

22) Create a boolean mask and list out the numbers that are not divisible by 3 in above array

In [102]:
mask = (arr % 3) != 0
arr[mask]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29])