NumPy is a linear algebra library. It is powerful and extremely fast and integrates with C/C++.

In [4]:
import numpy as np
np.__version__

'1.23.5'

**1) NumPy Arrays

NumPy Arrays can be used to form vectors and matrices

In [5]:
my_list = [-1, 0, 1]
my_list, type(my_list)

([-1, 0, 1], list)

In [6]:
my_array = np.array(my_list)
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [7]:
# lets create a 2d array
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my_2d_array, type(my_2d_array)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

In [8]:
# lets create a matrix from the 2d array
my_matrix = np.array(my_2d_array)
my_matrix, type(my_matrix)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

**1.2) NumPy Arrays from Tuples

In [9]:
my_list = np.array((1, 2, 3))
my_list

array([1, 2, 3])

**1.3) NumPy Array built-in methods**
Its common to create NumPy arrays using its own built-in methods.
They are much simpler and faster

**1.3.1) arange()**
arange is similar to range().
- used to generate evenly-spaced values in an interval
- syntax: arange([start ,] stop[, step,] dtype=None)

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.arange(0, 10, 2, float)

array([0., 2., 4., 6., 8.])

**1.3.2) linspace()**
similar to arange(), but the third argument for linspace is the number of points we want (instead of the step size)

In [13]:
np.linspace(1, 15, 4)

array([ 1.        ,  5.66666667, 10.33333333, 15.        ])

In [14]:
# a 4th optional argument returns the calculated step size alongside the array
my_linspace = np.linspace(1, 15, 3, retstep=True)
print('array is {arr}'.format(arr=my_linspace[0]))
print('step size is {step}'.format(step=my_linspace[1]))

array is [ 1.  8. 15.]
step size is 7.0


**1.3.3) zeros()**
Used to create an array or matrix with all zeroes

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((2, 3)) # row x col is passed in a tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

**1.3.4) ones()**
Used to create an array or matrix of ones (similar to zeros)

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((2, 3)) # row x col is passed in a tuple

array([[1., 1., 1.],
       [1., 1., 1.]])

**1.3.5) eye()**
Identity matrix, only one param is needed because its always a square matrix

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**1.3.6) rand()**
Create an array of a given shape and pick values over a uniform distribution

In [20]:
np.random.rand(3)

array([0.12868455, 0.48269446, 0.56206895])

In [21]:
np.random.rand(2, 3) # row x col, no tuple this time

array([[0.60890083, 0.36357831, 0.80453322],
       [0.85805344, 0.35978607, 0.62719152]])

**1.3.7) randn()**
Create an array of a given shape and pick values over a normal/Gaussian distribution

In [22]:
np.random.randn(3)

array([-1.23323834, -0.53074765,  1.30287217])

In [23]:
np.random.randn(2, 3)

array([[-0.04508046,  1.58042715, -0.93174633],
       [-0.53430189, -1.08752184, -0.8033654 ]])

**1.3.8) randint()**
Create an array of random ints from low (inclusive) to high (exclusive)

In [24]:
np.random.randint(1, 100)

22

In [25]:
# a third optional argument generates an array of random ints if provided
np.random.randint(1, 100, 10)

array([64, 32, 39, 96, 25, 64,  3, 88, 62, 79])

**2) Array methods and attributes**
reshape() -  can be used to convert an n element array into a x b array such that a x b = n
max() - find max value in array
min() - find min value in array
argmax() - find index of max value in array
argmin() - find index of min value in array

In [26]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
arr.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
arr2 = np.arange(11)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr2.reshape(11, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [30]:
arr3 = np.random.randint(1, 100, 10)
arr3

array([ 8, 83, 20, 47, 29, 95, 79,  6, 47, 48])

In [31]:
arr3.max()

95

In [32]:
arr3.argmax()

5

**3) Indexing & slicing

**3.1) 1-D arrays (vectors)

In [35]:
array_1d = np.array([-10, -2, 0, 2, 17, 106, 200])
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [36]:
# indexing
print('the value at index 0: ', array_1d[0])
print('the value at index -2: ', array_1d[-2])

the value at index 0:  -10
the value at index -2:  106


In [37]:
# grabbing a range
print('our original array is: ', array_1d)
print('our selected slice of the array is: ', array_1d[0:3])

our original array is:  [-10  -2   0   2  17 106 200]
our selected slice of the array is:  [-10  -2   0]


In [39]:
# this is weird, 
# but if you think of the end value as index (not direction)
# it makes sense
# -2 is same as index 4,
# so values from 1-4 are fetched, not 1, 0, -1, -2
print('our selected slice of the array is ', array_1d[1:-2])

our selected slice of the array is  [-2  0  2 17]


In [40]:
# we dont need to give start and end indices
print(array_1d[:2])
print(array_1d[2:])

[-10  -2]
[  0   2  17 106 200]


In [ ]:
# indices out of range cause index error
# array_id[305] # will cause an IndexError

**3.2) 2-D arrays (matrices)

In [41]:
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
# we can grab a row by passing a row number
array_2d[2]

array([ 8,  9, 10, 11])

In [43]:
# the same indexing works as with 1-D arrays
array_2d[-4]

array([ 8,  9, 10, 11])

In [44]:
# to get a single element specify array_2d[row][col]
array_2d[2, 3]

11

In [46]:
# to get a slice, 
# do array_2d[from_row:to_row_not_includes, from_col:to_col_not_includes]
array_2d[:2,:2] #gives a 2x2 matrix of first 2 cols and rows

array([[0, 1],
       [4, 5]])

**4) Broadcasting

In [47]:
# numpy arrays are different from python lists
# because of their ability to broadcast
array_1d = np.arange(0, 10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# lets broadcast 300 to the first five elements of array_1d
array_1d[0:5] = 300
print(array_1d)

[300 300 300 300 300   5   6   7   8   9]


In [55]:
# lets create a 2D matrix with ones
array_2d = np.ones((4, 4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
# lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [57]:
# lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0, 4)

array([[300., 301., 302., 303.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [58]:
# this wont work
array_2d + np.arange(0, 3)

ValueError: operands could not be broadcast together with shapes (4,4) (3,) 

In [59]:
array_2d + 300

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [60]:
array_2d + [300, 2]

ValueError: operands could not be broadcast together with shapes (4,4) (2,) 

In [62]:
array_1 = np.arange(1, 4)
array_2 = np.arange(1, 4)[:, np.newaxis]
print(array_1)
print("Shape of the array is {}, this is {}-D array".format(array_1.shape, len(array_1.shape)))

[1 2 3]
Shape of the array is (3,), this is 1-D array


In [63]:
print(array_2)
print("Shape of the array is {}, this is {}-D array".format(array_2.shape, len(array_2.shape)))

[[1]
 [2]
 [3]]
Shape of the array is (3, 1), this is 2-D array


In [64]:
# Broadcasting arrays
array_1 + array_2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [65]:
# lets try to break down whats happening
np.array([1, 2, 3]) + np.array([1])

array([2, 3, 4])

In [66]:
# lets try broadcasting a 1x3 array to 3x3 array
np.ones([3, 3]) + np.array([1, 2, 3])
# check figure of page 46 of pdf for visualization of broadcasting
# this is not the same as matrix + vector addition
# the right operand basically assumes the shape of the left
# and then does addition

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [67]:
# consider broadcasting a 3x1 array to a 1x3 array
np.ones([3, 1]) + np.arange(1, 4) 
# they both will fill to form a 3x3 array

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

**Fancy Indexing**
Fancy indexing allows use to select entire rows or columns out of order
Do you remember, zeros(), range(), shape and broadcasting?
Lets revise these concepts :)

In [68]:
array_2d = np.zeros((5, 5))
array_2d[1] = 1 # broadcasting 1 to second row at index 1
array_2d[2] = 2 # broadcasting 2 to third row at index 2
array_2d[3] = 3 # broadcasting 3 to fourth row at index 3
array_2d[4] = 4 # broadcasting 4 to fifth row at index 4
print(array_2d)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


The above process is tedious, lets try using a for-loop

In [69]:
array_2d = np.zeros((5, 5))
array_2d.shape[1]

5

In [70]:
for i in range(array_2d.shape[1]):
    array_2d[i] = i
array_2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

Fancy indexing allows us to grab any row using its index
Lets grab row 1, 2 and 3

In [71]:
array_2d[[1, 2, 3]]

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [72]:
# order isnt important
array_2d[[3, 0, 4]]

array([[3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [4., 4., 4., 4., 4.]])

In [76]:
# lets try fancy indexing with another example
array_2d = np.arange(24) # creating array using arange()
array_2d.shape = (6, 4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
# we can grab any random row, try 3 and 4
array_2d[[2, 4]]

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [80]:
# we can grab the columns as well
array_2d[:,[3, 2]] # grabs columns 3 and 2 in every row

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18],
       [23, 22]])

**5) Boolean masking**
5.1 Boolean mask arrays
Boolean mask is handy when counting, modifying, extracting or manipulating values in an array based on a certain condition/criteria
E.g. We want to count all the values greater than a certain value
We set a threshold and want to get-rid of outliers in the data

In [82]:
# Create a simple array using arange()
array_1d = np.arange(1, 11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
# we can apply condition such as >, <, == etc
# lets create a bool array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [85]:
# we can create a mask to filter out the even numbers in "array_1d"
mod_2_mask_id = (array_1d % 2) == 0
mod_2_mask_id

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

**5.2) Masking operation**
In masking operation, we simply index on the boolean array, that will return a 1D array filled with all the values that meet the condition
i.e. all the values in position at which the mask array, mod_2_mask_id is True

In [87]:
even_values = array_1d[mod_2_mask_id]
even_values

array([ 2,  4,  6,  8, 10])

In [88]:
# lets check with our array_2d
array_2d = np.arange(24)
array_2d.shape = (6, 4)
mask_mod_2_2d = (array_2d % 2) == 0 # masking
print(array_2d)
print(mask_mod_2_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [89]:
even_values_2d = array_2d[mask_mod_2_2d]
even_values_2d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

**6) Arithmetic operations**
We can perform arithmetic operations with NumPy arrays

In [91]:
# generate an array
arr = np.arange(0, 5)
arr

array([0, 1, 2, 3, 4])

In [92]:
arr + arr

array([0, 2, 4, 6, 8])

In [93]:
arr - arr

array([0, 0, 0, 0, 0])

In [94]:
arr * arr

array([ 0,  1,  4,  9, 16])

In [95]:
arr / arr # warning 0/0 is replaced with nan

C:\Users\asuch\AppData\Local\Temp\ipykernel_22764\4110895369.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr # warning 0/0 is replaced with nan


array([nan,  1.,  1.,  1.,  1.])

In [96]:
1 / arr # warning 1/0 is replaced with inf

C:\Users\asuch\AppData\Local\Temp\ipykernel_22764\1149331970.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr # warning 1/0 is replaced with inf


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [97]:
arr ** 2

array([ 0,  1,  4,  9, 16])

In [98]:
2 * arr

array([0, 2, 4, 6, 8])

**7) Universal functions**
NumPy have a range of built-in universal functions
They are essentially just mathematical operations
We can use them with NumPy arrays

In [99]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [100]:
np.max(arr), np.min(arr)

(4, 0)

In [101]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [102]:
np.exp(arr) # calculate the exponential (e^) of all elements in arr

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [103]:
np.log(arr)

C:\Users\asuch\AppData\Local\Temp\ipykernel_22764\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [104]:
np.deg2rad(arr) # convert angles from degrees to radians

array([0.        , 0.01745329, 0.03490659, 0.05235988, 0.06981317])

In [105]:
np.rad2deg(np.deg2rad(arr))

array([0., 1., 2., 3., 4.])